name: Update Threat Feeds

on:
  schedule:
    # Her 2 saatte bir çalışır (UTC zamanına göre)
    - cron: '0 */2 * * *'
  workflow_dispatch: # İsterseniz GitHub panelinden butonla elle de tetikleyebilirsiniz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-python-version: '3.x'

    - name: Run Fetch Script
      run: python fetch_threats.py

    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        git add threat_list.txt
        git diff-index --quiet HEAD || git commit -m "Auto-update threat list"
        git push
